Выполнил разметку главной страницы
htmlacademy-htmlcss/1626911-sedona-32 pull request #2
Opened 2021-09-28 12:41 UTC by kirill-nef

2е домашнее задание

2021-09-28 14:01 UTC, lawejr commented on index.html
> +    <a class="madein-utton" href="https://htmlacademy.ru/">
Опечатка в названии класса "-utton"
Ну и обычно такие блоки называют "copyright" :)

2021-09-28 14:02 UTC, lawejr commented on index.html
> +  <section class="footer-social">
Это относится ко всем секциям.

2021-09-28 14:09 UTC, lawejr commented on index.html
> +</body>
Тэг `body` вложен в `html`, поэтому отступ должен быть на одну табуляцию больше.

2021-09-28 17:28 UTC, kirill-nef commented on index.html
> +        <a href="#" class="navigation-link">Главная</a>
Что-то не могу понять зачем так делать) ведь по макету задумано, что будет именно ссылка.

Можно просто создать класс, который будет блочить клик.

2021-09-28 17:29 UTC, kirill-nef commented on index.html
> +    <img class="logo_icon" src="" alt="Логотип Седоны">
Согласен

2021-09-28 17:33 UTC, kirill-nef commented on index.html
> +  <img class="logo_main" src="" alt="Логотип приветствия Седоны">
дурная привычка) исправлю

2021-09-28 17:34 UTC, kirill-nef commented on index.html
> +    <ul class="description-list">
то есть надо через тег ul лучше сделать?

2021-09-28 17:36 UTC, kirill-nef commented on index.html
> +  <img class="mailing-logo" src="" alt="Картинка с изображением гор">
согласен! понял смысл

2021-09-28 18:45 UTC, lawejr commented on index.html
> +        <a href="#" class="navigation-link">Главная</a>
А можно убрать атрибут и не создавать дополнительный класс. Кода меньше и понятней:)

2021-09-28 18:47 UTC, lawejr commented on index.html
> +    <ul class="description-list">
Да

2021-09-29 03:27 UTC, kirill-nef commented on index.html
> +    <img class="logo_icon" src="" alt="Логотип Седоны">
Выполнено!

2021-09-29 03:30 UTC, kirill-nef commented on index.html
> +    </button>
Выполнено!

2021-09-29 03:40 UTC, kirill-nef commented on index.html
> +</main>
Выполнено!

2021-09-29 03:44 UTC, kirill-nef commented on index.html
> +          <span class="visually-hidden">like</span>
Выполнено!

2021-09-29 03:54 UTC, kirill-nef commented on index.html
> +  <img class="logo_main" src="" alt="Логотип приветствия Седоны">
Выполнено!

2021-09-29 03:56 UTC, kirill-nef commented on index.html
> +    <ul class="description-list">
А то что у меня внутри каждой карточки уже создан список, лучше его как-нибудь по другому записать?

2021-09-29 04:06 UTC, kirill-nef commented on index.html
> +  <button class="search-button slider-prev" type="button">
`SPAN` переделать в `A` ?
или вообще от button избавиться?

2021-09-29 04:11 UTC, kirill-nef commented on index.html
> +  <img class="mailing-logo" src="" alt="Картинка с изображением гор">
Выполнено!

Наверное мы потом как background в css зададим? но тут надо учесть, если картинка не загрузится, тогда мы не увидим белый текст, надо будет фону в этом блоке цвет задать

2021-09-29 04:23 UTC, kirill-nef commented on index.html
> +      <input class="field" type="text" id="mailing-form-mail" name="mailing-form-mail" placeholder="Ваш e-mail" >
Выполнено!

2021-09-29 04:27 UTC, kirill-nef commented on index.html
> +</body>
Выполнил!

Кстати автоматическое форматирование выдерживает `html` и `body` на одном уровне

2021-09-29 04:33 UTC, kirill-nef commented on index.html
> +    <a class="madein-utton" href="https://htmlacademy.ru/">
Выполнено!

2021-09-29 04:39 UTC, kirill-nef commented on index.html
> +          <img src="#" alt="Твиттер">
Выполнено!

2021-09-29 04:48 UTC, kirill-nef commented on index.html
> +  <section class="footer-social">
Выполнено! 

Что-то мне не нравится так делать) но может потом со временем придёт.

2021-09-29 04:48 UTC, kirill-nef commented on index.html
> +  <section class="footer-social">
Выполнено! 

Что-то мне не нравится так делать) но может потом со временем придёт.

2021-09-29 06:46 UTC, kirill-nef commented on index.html
> +      <input class="field" type="text" id="mailing-form-mail" name="mailing-form-mail" placeholder="Ваш e-mail" >
Выполнено! да потерял где то, глаз замылился)))

2021-09-29 06:47 UTC, kirill-nef commented on index.html
> +        <a href="#" class="navigation-link">Главная</a>
Нужна консультация)

2021-09-29 13:41 UTC, lawejr requested changes

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <img class="hotels_card_image" src="#" alt="Desert Quail Inn">
Картинки тоже должны быть ссылками, по макету у них есть разные состояния в стайлгайде https://www.figma.com/file/XTA1QAD4FQmJCRtbNbGbPb/HTML-1-Седона-32?node-id=476%3A200

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <button class="button" type="submit">Избранное</button>
Кнопки в макетах называются "В избранное", а добавленные "В избранном"

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <a href="#" class="hotels_detail_button button">Подробно</a>
А эти кнопки называются "Подробнее", будь внимательней

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <button class="button" type="submit">Избранное</button>
Здесь не нужен `type="submit"`, т.к. кнопка не отправляет никакую форму.
И я бы рекомендовал их тоже сделать ссылками, это позволит им работать без JS. Аналогично добавлениям товаров в корзину на лекции.

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <b class="hotels_card_price">от 3000₽</b>
"От" с заглавной буквы

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <img class="hotels_card_stars" src="#" alt="2 stars">
Звёзды лучше сделать с помощью списка отдельных звёзд. Причём сделать их потом через css, а не `<img>`. Это позволит тебе не использовать много картинок для каждого количества звёзд(1star.png, 2star.png, 3star.png и тд). У тебя будет всего одна картинка и ты сможешь задать любое количество звёзд с её помощью.

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +            <button class="button" type="submit">Загрузить ещё</button>
Здесь тоже нет никаких формы и `type="submit"` не нужен. 
Ну и лучше сделать ссылкой, которая просто ведёт на следующую страницу, чтобы она могла работать без JS.

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                <h3 class="page_hotels_title">2</h3>
А почему ты решил, что это заголовки? Я бы сделал это просто текстом внутри ссылки без дополнительных тегов.

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <a href="hotels.html" class="navigation_link">Гостинницы</a>
Обрати внимание на порядок атрибутов. `class` всегда должен идти первым по кодгайду http://codeguide.academy/html-css.html#html-attr-order

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <a href="#" class="navigation_link">Главная</a>
Здесь можно заполнить `href`, чтобы страница вела на index.html, ведь у нас есть такая страница

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <a href="hotels.html" class="navigation_link">Гостинницы</a>
Нужно удалить `href`, т.к. мы уже находимся на странице `hotels.html` и ссылка не должна быть активной.
Так же для ссылок без `href` рекомендуется прописывать подсказку в виде атрибута `title`. Подробнее здесь https://up.htmlacademy.ru/htmlcss/32/module/2/item/4/15 .

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                <label class="visually_hidden" for="quantity">Колличество отелей на странице</label>
А у нас же по макету есть подобный лейбл. Зачем ты его сделал скрытым?

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                    <option value="all">Все</option>
Это не ошибка, но обычно так не делают. Если ты запросишь все возможные отели, ты просто повесишь сайт)))

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +            </form>
Не хватает скрытой кнопки для отправки формы, аналогично тому, что я писал в фильтрах

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                </p>
Что-то тут напутано с тэгами. Пустой `<p>` вверху. Здесь лишний закрывающий `<p>`.

2021-09-29 13:41 UTC, lawejr commented on hotels.html
> +                <button class="mailing_button" type="submit">Записаться</button>
Текст в кнопке на макете другой

2021-09-30 04:42 UTC, kirill-nef commented on index.html
> +        <a href="#" class="navigation-link">Главная</a>
Выполнено!

На странице hotels так же внес правку

2021-09-30 04:52 UTC, kirill-nef commented on index.html
> +    <ul class="description-list">
Выполнено! но сомневаюсь, что это правильно. Можно ли внутри списка создавать еще список?!

2021-09-30 04:58 UTC, kirill-nef commented on index.html
> +  <button class="search-button slider-prev" type="button">
Я понял, что кнопки с одним функционалом но немного с разным оформлением, просто при стилизации можно будет каждой кнопке добавить еще по классу и подогнать под макет.

Выполнено!

2021-09-30 05:06 UTC, kirill-nef commented on hotels.html
> +    <title>HTML Academy: Гостинницы</title>
Выполнено!

2021-09-30 05:16 UTC, kirill-nef commented on hotels.html
> +                        <a class="breadcrumbs_link" href="index.html">Главная</a>
Тут должна быть такая надпись "Гостиницы Седоны"! поменял надпись и скрывать на стал, так как на макете она есть))

Выполнено!

2021-09-30 05:32 UTC, kirill-nef commented on hotels.html
> +            <fieldset class="catalog-filter-group">
Да точно! исправил

Выполнено!

2021-09-30 05:37 UTC, kirill-nef commented on hotels.html
> +
Исправил))

Выполнено!

2021-09-30 05:48 UTC, kirill-nef commented on hotels.html
> +                <button class="button" type="submit">Сбросить</button>
Спасибо! буду знать, исправил!

Выполнено!

2021-09-30 05:52 UTC, kirill-nef commented on hotels.html
> +                    <option value="cheap">Сначала дешёвое</option>
Как показал мой внутренний анализ, во всем мире сначала идет сортировка по популярным))) это в макете ошибка!! 

Так и быть, исправил!

Выполнено!

2021-09-30 06:05 UTC, kirill-nef commented on hotels.html
> +                    <option value="expensive">Сначала дорогое</option>
Выполнено!

2021-09-30 06:07 UTC, kirill-nef commented on hotels.html
> +            <h2 class="visually_hidden">Карточки гостинниц</h2>
Выполнено!

2021-09-30 06:10 UTC, kirill-nef commented on hotels.html
> +                    <img class="hotels_card_image" src="#" alt="Amara Resort & Spa">
буду иметь ввиду)) делал по каким то соображениям, как заполняли пустые ссылки у тега` а`

Выполнено!

2021-09-30 06:33 UTC, kirill-nef commented on hotels.html
> +                    <a class="hotels_card_link" href="hotels.html">
Выполнено!

2021-09-30 06:43 UTC, kirill-nef commented on hotels.html
> +                    <img class="hotels_card_image" src="#" alt="Desert Quail Inn">
Суть понял.. исправил

Выполнено!

2021-09-30 08:06 UTC, kirill-nef commented on hotels.html
> +                    <button class="button" type="submit">Избранное</button>
Выполнено!

2021-09-30 08:09 UTC, kirill-nef commented on hotels.html
> +                    <a href="#" class="hotels_detail_button button">Подробно</a>
Выполнено!

2021-09-30 08:09 UTC, kirill-nef commented on hotels.html
> +                    <b class="hotels_card_price">от 3000₽</b>
Выполнено!

2021-09-30 08:16 UTC, kirill-nef commented on hotels.html
> +                    <img class="hotels_card_stars" src="#" alt="2 stars">
Не уверен что правильно сделал! но кажется так можно будет реализовать такую идею!

Выполнено!

2021-09-30 08:22 UTC, kirill-nef commented on hotels.html
> +            <button class="button" type="submit">Загрузить ещё</button>
Выполнено!

2021-09-30 09:43 UTC, kirill-nef commented on hotels.html
> +                <h3 class="page_hotels_title">2</h3>
Странно что я так сделал. Ведь на уроке показывали делать по другому!
Исправил!
Выполнено!

2021-09-30 09:57 UTC, kirill-nef commented on hotels.html
> +                    <a href="hotels.html" class="navigation_link">Гостинницы</a>
СТолько всего! я не знаю как это запомнить)))

Выполнено!

2021-09-30 10:01 UTC, kirill-nef commented on hotels.html
> +                    <a href="#" class="navigation_link">Главная</a>
Выполнено!

2021-09-30 10:15 UTC, kirill-nef commented on hotels.html
> +                <label class="visually_hidden" for="quantity">Колличество отелей на странице</label>
Ошибся, исправил!

Выполнено!

2021-09-30 10:16 UTC, kirill-nef commented on hotels.html
> +                    <option value="all">Все</option>
Да в этой седоне вообще столько отелей нет чтобы наш сервак положить)))) исправил

Выполнено!

2021-09-30 10:18 UTC, kirill-nef commented on hotels.html
> +            </form>
Выполнено!

2021-09-30 10:23 UTC, kirill-nef commented on hotels.html
> +                </p>
Выполнено!

2021-09-30 10:23 UTC, kirill-nef commented on hotels.html
> +                <button class="mailing_button" type="submit">Записаться</button>
Выполнено!

2021-09-30 12:51 UTC, lawejr commented on index.html
> +          <a class="navigation_link" title="Ты и так на этой странице">Главная</a>
Давай как-то без поуважительней будем пользователю подсказывать:)))

2021-09-30 12:51 UTC, lawejr commented on index.html
> +      <a href="index.html" class="logo_link">
Здесь не нужен атрибут href, ты же сейчас находишься на index.html

2021-10-01 10:40 UTC, lawejr requested changes

2021-10-01 10:40 UTC, lawejr commented on hotels.html
> +            <a class="breadcrumbs-link" href="index.html">Главная</a>
Не исправлено https://github.com/htmlacademy-htmlcss/1626911-sedona-32/pull/2#discussion_r718467123

2021-10-01 10:40 UTC, lawejr commented on hotels.html
> +          <a class="navigation-link" href="">
Пустых `href` у ссылок быть не должно. Если страницы на которую ведёт ссылка нет, нужно поставить заглушку в виде "#"

2021-10-01 10:40 UTC, lawejr commented on hotels.html
> +      <fieldset class="catalog-filter-group">
А fieldset открывающий забыл внутрь формы включить?

2021-10-01 10:40 UTC, lawejr commented on index.html
> +          <a class="navigation-link" title="Красиво, не правда-ли?">Главная</a>
Это всё, конечно, весело:) Но как такая подсказка поможет понять пользователю, почему он не может нажать на эту ссылку?
Напиши что-то типа: "Вы сейчас находится на этой странице".

2021-10-01 10:43 UTC, lawejr requested changes
Не все замечания исправлены

2021-10-01 10:48 UTC, kirill-nef commented on index.html
> +        <img class="logo_icon" title="Красиво, не правда-ли?" alt="Логотип Седоны">
Выполнено!

2021-10-01 10:53 UTC, kirill-nef commented on index.html
> +        <button class="navigation_button" type="button">
Почему то думал это будет кнопка и будет вылазить поверх окно с поиском и тд
Исправил
Выполнено!

2021-10-01 10:55 UTC, kirill-nef commented on index.html
> +    <h1 class="visually_hidden">Блок описания из карточек и картинок</h3>
Выполнено!

2021-10-01 11:00 UTC, kirill-nef commented on index.html
> +        <button class="navigation_button" type="button">
Кнопку "поиск гостинниц в седоне" заменил на ссылку

2021-10-01 11:00 UTC, kirill-nef commented on index.html
> +        <button class="navigation_button" type="button">
Выполнено!

2021-10-01 15:22 UTC, kirill-nef commented on index.html
> +              <ul class="description_list">
Выполнено!

2021-10-01 15:26 UTC, kirill-nef commented on index.html
> +    <h2 class="visually_hidden">Ссылки на соцсети</h2>
Понял зачем!

Выполнено!

2021-10-01 15:26 UTC, kirill-nef commented on index.html
> +    <h2 class="visually_hidden">Ссылки на соцсети</h2>
Понял зачем!

Выполнено!

2021-10-01 15:39 UTC, kirill-nef commented on hotels.html
> +            <fieldset class="catalog-filter-group">
Выполнил!

2021-10-01 15:43 UTC, kirill-nef commented on hotels.html
> +            <form  class="sorting_type" action="https://echo.htmlacademy.ru/" method="get">
Выполнено!

2021-10-01 15:48 UTC, kirill-nef commented on hotels.html
> +          <a class="navigation-link" href="">
Выполнено!

2021-10-01 15:51 UTC, kirill-nef commented on index.html
> +          <a class="navigation-link" title="Красиво, не правда-ли?">Главная</a>
Выполнено!

2021-10-01 15:54 UTC, kirill-nef commented on hotels.html
> +      <fieldset class="catalog-filter-group">
Выполнено!

2021-10-01 16:00 UTC, kirill-nef commented on hotels.html
> +                    <h3 class="visually_hidden">2 stars</h3>
хорошо! я теперь понял суть заголовков)

Выполнено!

2021-10-01 16:02 UTC, kirill-nef commented on hotels.html
> +                <label class="quantity_title" for="quantity">Колличество отелей на странице</label>
Привычка де ЛЛ везде писать)) всё из-за моего имени

2021-10-01 16:02 UTC, kirill-nef commented on hotels.html
> +                <label class="quantity_title" for="quantity">Колличество отелей на странице</label>
Выполнено!

2021-10-01 16:16 UTC, kirill-nef commented on hotels.html
> +                     <ul class="hotels_stars">
Может что-то посоветуешь!? я пользуюсь встроенным форматированием, оно срабатывает только по моему требованию... не нравится что он еще переносит длинные строки

2021-10-01 16:16 UTC, kirill-nef commented on hotels.html
> +                <ul class="catalog_filter_list">
Вроде бы всё исправил!

2021-10-01 16:17 UTC, kirill-nef commented on hotels.html
> +                        <a class="breadcrumbs_link" href="index.html">Главная</a>
Выполнено!

2021-10-01 16:19 UTC, kirill-nef commented on hotels.html
> +    <header class="page_header">
Выполнено!

2021-10-02 08:36 UTC, lawejr requested changes

2021-10-02 08:36 UTC, lawejr commented on hotels.html
> +              <img class="breadcrumbs-icon" src="" alt="Главная">
Иконка это декоративный элемент, его можно сделать через `background-image`, как иконки соц.сетей в футере.

2021-10-02 08:36 UTC, lawejr commented on hotels.html
> +            <li class="hotels-stars-item">
Форматирование не исправлено. Поправь пока вручную. На консультации обсудим, как сделать так, чтобы форматирование работало автоматически. Запиши этот вопрос в свой список.

2021-10-02 08:36 UTC, lawejr commented on hotels.html
> +        <label class="quantity-title" for="quantity">Количество отелей на странице</label>
Ну другой же текст здесь! Третий раз пишу. Посмотри макет!

2021-10-02 08:36 UTC, lawejr commented on index.html
> +        <img class="logo-icon" src="#" title="Вы сейчас находитесь на этой странице" alt="Логотип Седоны">
У картинок не надо писать никаких подсказок `title`. Такие подсказки нужны у ссылок без атрибута `href` https://up.htmlacademy.ru/htmlcss/32/module/3/item/14/15
В данном случае можешь на своё усмотрение либо просто удалить `title`, либо перенести его в ссылку.

2021-10-02 08:36 UTC, merged

2021-10-03 05:12 UTC, kirill-nef commented on hotels.html
> +              <img class="breadcrumbs-icon" src="" alt="Главная">
Понял!

Выполнено!

2021-10-03 05:18 UTC, kirill-nef commented on hotels.html
> +            <li class="hotels-stars-item">
Давай лучше на консультации и исправлю, а то потом автоматом опять так выставится...

2021-10-03 05:23 UTC, kirill-nef commented on hotels.html
> +        <label class="quantity-title" for="quantity">Количество отелей на странице</label>
Прости наставник!

Выполнено!

2021-10-03 05:27 UTC, kirill-nef commented on index.html
> +        <img class="logo-icon" src="#" title="Вы сейчас находитесь на этой странице" alt="Логотип Седоны">
Выполнено!