Декоративные элементы на главной странице
htmlacademy-htmlcss/1626911-sedona-32 pull request #8
Opened 2021-11-01 06:27 UTC by kirill-nef

2021-11-02 08:39 UTC, lawejr requested changes

2021-11-02 08:39 UTC, lawejr commented on images/other/Direction.svg
> +</svg>
Изображение не оптимизировано

2021-11-02 08:39 UTC, lawejr commented on index.html
> +            title="Вы сейчас находитесь на главной странице">Главная</a>
Здесь поехали отступы. Лучше в такой ситуации просто текст ссылки и закрывающий тэг расположить на отдельных строках

2021-11-02 08:39 UTC, lawejr commented on index.html
> +      <a class="logo-link" title="Вы сейчас находитесь на главной странице"></a>
Логотип это достаточно важное контентное изображение. Лучше оставить его самостоятельным тэгом. Фоном делаем декоративные картинки, которые не несут никакого смысла для пользователя.

2021-11-02 08:39 UTC, lawejr commented on index.html
> +          <a class="navigation-link-icon" href="#">
<img width="305" alt="Снимок экрана 2021-11-02 в 13 16 16" src="https://user-images.githubusercontent.com/16274554/139810027-29dfdb11-69b9-4255-aec8-3013fa829f96.png">
<img width="247" alt="Снимок экрана 2021-11-02 в 13 16 49" src="https://user-images.githubusercontent.com/16274554/139810083-5cc0dd5e-1aa5-47f0-9ac5-bc393d429c1a.png">
форма и размеры обводки при фокусе не совпадают с макетом. Проверь ещё раз все элементы по стайлгайду

2021-11-02 08:39 UTC, lawejr commented on index.html
> +          <a class="navigation-link-icon" href="#">
Есть аналогичные несоответствия у элементов футера

2021-11-02 08:39 UTC, lawejr commented on index.html
>          <input class="mailing-field" type="email" id="mailing-form-mail" name="mailing-form-mail"
<img width="649" alt="Снимок экрана 2021-11-02 в 13 20 28" src="https://user-images.githubusercontent.com/16274554/139810578-e1becfb4-2c85-4770-98ff-1ed30b4f5816.png">
<img width="696" alt="Снимок экрана 2021-11-02 в 13 20 15" src="https://user-images.githubusercontent.com/16274554/139810593-1f007cdf-b41c-47b4-bc83-4817dea4a2d5.png">

Обводка инпута при фокусе должна быть за его границами, а на она странице реализована внутри инпута

2021-11-02 08:39 UTC, lawejr commented on index.html
> +      <div class="welcome-decor-bottom"></div>
Можно сделать через псевдоэлемент, чтобы не плодить пустые тэги

2021-11-02 08:39 UTC, lawejr commented on index.html
>          <input class="mailing-field" type="email" id="mailing-form-mail" name="mailing-form-mail"
Аналогичная ситуация с некоторыми кнопками

2021-11-02 08:39 UTC, lawejr commented on index.html
> +            <div class="card-icon card-icon-home"></div>
Можно сделать через псевдоэлемент, чтобы не плодить лишние пустые тэги

2021-11-02 08:39 UTC, lawejr commented on styles/styles.css
> +  background-position: center;
Свойства `background-repeat` и `background-position` можно вынести в общий класс `.card-icon`, т.к. они одинаковые и повторяются. А в классах `.card-icon-*` оставить только `background-image`, т.к. только это свойство изменяется.

2021-11-02 08:39 UTC, lawejr commented on styles/styles.css
> +.hotels-buttons .button + .button {
Что-то слишком сложный селектор получается. Лучше кнопкам дополнительно задать новые класс и стилизовать его без вложенности. Например `.hotels-button + .hotels-button`.

2021-11-03 05:19 UTC, kirill-nef commented on index.html
> +            title="Вы сейчас находитесь на главной странице">Главная</a>
Исправил!

2021-11-03 06:17 UTC, kirill-nef commented on index.html
> +      <a class="logo-link" title="Вы сейчас находитесь на главной странице"></a>
Исправил!

2021-11-03 06:31 UTC, kirill-nef commented on index.html
> +          <a class="navigation-link-icon" href="#">
Нужна помощь, записываюсь на консультацию

2021-11-03 07:28 UTC, kirill-nef commented on index.html
> +      <div class="welcome-decor-bottom"></div>
Исправил!

2021-11-03 10:08 UTC, kirill-nef commented on index.html
> +          <a class="navigation-link-icon" href="#">
Выполнено путём уменьшения паддингов!

2021-11-03 10:08 UTC, kirill-nef commented on index.html
>          <input class="mailing-field" type="email" id="mailing-form-mail" name="mailing-form-mail"
Поправил!

2021-11-03 10:09 UTC, kirill-nef commented on index.html
> +            <div class="card-icon card-icon-home"></div>
Исправил!

2021-11-03 10:09 UTC, kirill-nef commented on styles/styles.css
> +  background-position: center;
Исправил!

2021-11-04 08:40 UTC, lawejr requested changes

2021-11-04 08:40 UTC, lawejr commented on images/favicon.svg
> +<path d="M17.3457 16.0727C16.7639 16.4 16.2184 15.1636 17.2366 15.2727C17.8912 15.3454 18.5821 15.2 19.2002 15.3091C18.7275 15.8545 18.073 16.1454 17.3457 16.0727Z" fill="#F4B1A4"/>
Изображение не оптимизировано

2021-11-04 08:40 UTC, lawejr commented on index.html
> +  <!-- <link rel="shortcut icon" type="image/x-icon" href="https://htmlacademy.ru/favicon.svg"> -->
В файлах не должно быть закомментированного кода

2021-11-04 08:41 UTC, merged

2021-11-05 06:43 UTC, kirill-nef commented on images/favicon.svg
> +<path d="M17.3457 16.0727C16.7639 16.4 16.2184 15.1636 17.2366 15.2727C17.8912 15.3454 18.5821 15.2 19.2002 15.3091C18.7275 15.8545 18.073 16.1454 17.3457 16.0727Z" fill="#F4B1A4"/>
Исправил!

2021-11-05 06:43 UTC, kirill-nef commented on index.html
> +  <!-- <link rel="shortcut icon" type="image/x-icon" href="https://htmlacademy.ru/favicon.svg"> -->
Исправил!