Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1626911-sedona-32 pull request #9
Opened 2021-11-05 06:45 UTC by kirill-nef

2021-11-06 16:17 UTC, lawejr requested changes

2021-11-06 16:17 UTC, lawejr commented on styles/styles.css
> +  appearance: textfield;
Кажется, это значение свойства не принято в стандарты css. Для чего оно используется?
Думаю, можно обойтись без него.

2021-11-06 16:17 UTC, lawejr commented on hotels.html
>            </fieldset>
<img width="274" alt="Снимок экрана 2021-11-06 в 21 05 52" src="https://user-images.githubusercontent.com/16274554/140616120-0bde2c29-89d7-47be-af82-0f82204cb1c0.png">
Не стилизованы активные состояния этих элементов.

2021-11-06 16:17 UTC, lawejr commented on hotels.html
>        </form>
<img width="341" alt="Снимок экрана 2021-11-06 в 21 07 36" src="https://user-images.githubusercontent.com/16274554/140616146-861b9951-543b-4a4a-bd24-8f91b8aa4b60.png">
В сафари не работает состояние наведения из-за неправильной структуры тэгов. Лучше расположить ссылку внутри заголовка, а не заголовок внутри ссылки. Тогда и селектор в css получится проще.

2021-11-06 16:17 UTC, lawejr commented on hotels.html
>        </form>
<img width="204" alt="Снимок экрана 2021-11-06 в 21 14 57" src="https://user-images.githubusercontent.com/16274554/140616386-50d254b1-8a9f-47ce-a053-95012c807fa0.png"
<img width="305" alt="Снимок экрана 2021-11-06 в 21 14 44" src="https://user-images.githubusercontent.com/16274554/140616389-52c87e38-7c67-4b9c-bdf5-7d1476dd9ca9.png">
>
Стилизация наведения кнопок не соответствует макету

2021-11-07 07:20 UTC, kirill-nef commented on styles/styles.css
> +  box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);
Исправил! оставил все в хекс

2021-11-07 07:20 UTC, kirill-nef commented on styles/styles.css
> +  background-image: url(../images/other/checked.svg);
Исправил!

2021-11-07 07:45 UTC, kirill-nef commented on styles/styles.css
> +  appearance: textfield;
https://youtu.be/lL59kgUK-qM?t=4768

на уроке не объяснили что это(( я тоже решил вставить

2021-11-07 07:52 UTC, kirill-nef commented on hotels.html
>            </fieldset>
![image](https://user-images.githubusercontent.com/88302370/140636980-6e71ded0-73b6-4813-8b79-748c4148d105.png)
вроде всё по макету - тот вид, который является включенным сейчас, является активным. В данном случае черный бордер этому свидетельствует

2021-11-07 07:59 UTC, kirill-nef commented on hotels.html
>        </form>
Не понял тоже, всё по макету...

2021-11-07 09:42 UTC, kirill-nef commented on hotels.html
>        </form>
Исправил!

2021-11-07 13:54 UTC, kirill-nef commented on styles/styles.css
> +  appearance: textfield;
Для мозиллы это нужно, иначе стрелочки у инпута не уберутся

2021-11-08 05:41 UTC, lawejr commented on styles/styles.css
> +  appearance: textfield;
Добавь префикс -moz-, чтобы работало в более старых версиях FF

2021-11-08 05:42 UTC, merged